# Generated by Django 2.2.3 on 2019-07-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190705_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_mohth',
            new_name='birth_month',
        ),
    ]
